# Generated by Django 4.1.7 on 2023-03-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('c_email', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Servicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('service_image', models.ImageField(default='null.jpg', upload_to='Service')),
            ],
        ),
        migrations.CreateModel(
            name='Venuedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=700)),
                ('manager', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('services', models.CharField(max_length=20)),
                ('venue_img', models.ImageField(default='null.jpg', upload_to='Venue')),
            ],
        ),
    ]
