# Generated by Django 4.1.7 on 2023-03-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedb',
            name='cost',
            field=models.CharField(max_length=30),
        ),
    ]
