# Generated by Django 4.1.7 on 2023-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_alter_servicedb_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuedb',
            name='manager',
            field=models.CharField(default='', max_length=100),
        ),
    ]
