# Generated by Django 4.1.5 on 2023-03-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_alter_venuedb_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Managerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_name', models.CharField(max_length=500)),
                ('man_address', models.CharField(max_length=700)),
                ('man_phone', models.IntegerField()),
                ('venue_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('manager_image', models.ImageField(default='null.jpg', upload_to='Manager')),
            ],
        ),
    ]
