# Generated by Django 3.2.16 on 2023-03-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_managerdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Managerdb',
        ),
    ]
