# Generated by Django 4.1.2 on 2023-03-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0006_managerdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuedb',
            name='services',
        ),
    ]
