# Generated by Django 4.1.2 on 2023-03-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_booking_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_service',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_amount',
            field=models.IntegerField(default=0),
        ),
    ]
