# Generated by Django 4.1.2 on 2023-03-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_booking_selected_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
