# Generated by Django 4.1.2 on 2023-03-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_booking_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
