# Generated by Django 4.1.6 on 2023-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.CharField(default='', max_length=30),
        ),
    ]
